%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\JOrsmond\MATLAB\Projects\masters\data\kaggle\wine-clustering.csv
%
% Auto-generated by MATLAB on 09-Feb-2022 15:08:08

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 13);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Alcohol", "Malic_Acid", "Ash", "Ash_Alcanity", "Magnesium", "Total_Phenols", "Flavanoids", "Nonflavanoid_Phenols", "Proanthocyanins", "Color_Intensity", "Hue", "OD280", "Proline"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
wineclustering = readtable("C:\Users\Jedd\Documents\MATLAB\masters\dataCommit\kaggle\wine-clustering.csv", opts);


%% Clear temporary variables
clear opts