function [labels, dataset_raw, dataset_std, PC, coeff, score, explained] = ImportDataSet(target)
%convenience function to import different datasets for Clustering testing
%will import the raw data, standardize it and then return the PCs

%target = source
%1 = Penicillin Fermentation Process (small = 5 datasets)
%2 = Penicillin Fermentation Process (large = 50 datasets)
%3 = Kaggle Wine Dataset
%4 = Hald (built-in matlab dataset for ingredients)

addpath 'C:\Users\JOrsmond\MATLAB\Projects\masters'\dataCommit\;
addpath 'C:\Users\JOrsmond\MATLAB\Projects\masters\2 - Preprocess Data'

if target == 1 || target==2
    inputVars = ["CL", "CO2", "S", "T", "V", "pH", "X", "F", "Pw"];
    outputVars = ["P"];

    if target==1
        load ('dataCommit\five_historicalbatches_aligned_trimmed_unfolded.mat');
    else
        load ('dataCommit\50_historicalbatches_aligned_trimmed_unfolded.mat');
    end
    [inputTable, outputTable] = SplitTables(unfolded, inputVars, outputVars);
    inputMatrix = table2array(inputTable);
    dataset_raw = inputMatrix;
    [dataset_std, centers, scales] = StandardizeUnfolded(inputTable);
    dataset_std = table2array(dataset_std);
    [coeff, score, latent, tsquared, explained, mu, PC] = RunPCA( dataset_std );
    labels = inputVars;

elseif target == 3
    %https://www.kaggle.com/harrywang/wine-dataset-for-clustering
    %https://medium.com/swlh/k-means-clustering-on-high-dimensional-data-d2151e1a4240
    %13 variables (chemical qualities) of several wines in 3 different wine types
    % % The attributes are:
    % %
    % % Alcohol
    % % Malic acid
    % % Ash
    % % Alcalinity of ash
    % % Magnesium
    % % Total phenols
    % % Flavanoids
    % % Nonflavanoid phenols
    % % Proanthocyanins
    % % Color intensity
    % % Hue
    % % OD280/OD315 of diluted wines
    % % Proline

    %% Import data from text file
    % Script for importing data from the following text file:
    %
    %    filename: C:\Users\JOrsmond\MATLAB\Projects\masters\data\kaggle\wine-clustering.csv
    %
    % Auto-generated by MATLAB on 09-Feb-2022 15:08:08

    %% Set up the Import Options and import the data
    opts = delimitedTextImportOptions("NumVariables", 13);

    % Specify range and delimiter
    opts.DataLines = [2, Inf];
    opts.Delimiter = ",";

    % Specify column names and types
    opts.VariableNames = ["Alcohol", "Malic_Acid", "Ash", "Ash_Alcanity", "Magnesium", "Total_Phenols", "Flavanoids", "Nonflavanoid_Phenols", "Proanthocyanins", "Color_Intensity", "Hue", "OD280", "Proline"];
    opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

    % Specify file level properties
    opts.ExtraColumnsRule = "ignore";
    opts.EmptyLineRule = "read";

    % Import the data
    dataset_raw = readtable("C:\Users\JOrsmond\MATLAB\Projects\masters\dataCommit\kaggle\wine-clustering.csv", opts);
    [dataset_std, centers, scales] = StandardizeUnfolded(dataset_raw);
    dataset_std = table2array(dataset_std);
    [coeff, score, latent, tsquared, explained, mu, PC] = RunPCA( dataset_std );
    labels = opts.VariableNames;

    %% Clear temporary variables
    clear opts
elseif target==4
%     '== Portland Cement Data ==                                '
%         '                                                          '
%         'Multiple regression data                                  '
%         '                                                          '
%         'ingredients (%):                                          '
%         'column1: 3CaO.Al2O3 (tricalcium aluminate)                '
%         'column2: 3CaO.SiO2 (tricalcium silicate)                  '
%         'column3: 4CaO.Al2O3.Fe2O3 (tetracalcium aluminoferrite)   '
%         'column4: 2CaO.SiO2 (beta-dicalcium silicate)              '
%         '                                                          '
%         'heat (cal/gm):                                            '
%         'heat of hardening after 180 days                          '
%         '                                                          '
%         'Source:                                                   '
%         'Woods,H., H. Steinour, H. Starke,                         '
%         '"Effect of Composition of Portland Cement on Heat Evolved '
%         'during Hardening," Industrial and Engineering Chemistry,  '
%         'v.24 no.11 (1932), pp.1207-1214.                          '
%         '                                                          '
%         'Reference:                                                '
%         'Hald,A., Statistical Theory with Engineering Applications,'
%         'Wiley, 1960.  

    load hald;
    dataset_raw = ingredients;
    [dataset_std, centers, scales] = StandardizeUnfolded(dataset_raw);
    [coeff, score, latent, tsquared, explained, mu, PC] = RunPCA( dataset_std );
    labels = ["Al2O3", "SiO2", "Fe2O3", "2SiO2"];
end

